grids = {
    "standard": {
        "superchargedFixed": False,
        "gridFixed": False,
        "grid": [
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
        ],
    },
    "sentinel": {
        "superchargedFixed": False,
        "gridFixed": False,
        "grid": [
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
        ],
    },
    "solar": {
        "superchargedFixed": False,
        "gridFixed": False,
        "grid": [
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
        ],
    },
    "living": {
        "superchargedFixed": False,
        "gridFixed": False,
        "grid": [
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
        ],
    },
    "standard-mt": {
        "superchargedFixed": False,
        "gridFixed": False,
        "grid": [
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
        ],
    },
    "atlantid": {
        "superchargedFixed": False,
        "gridFixed": False,
        "grid": [
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
        ],
    },
    "sentinel-mt": {
        "superchargedFixed": False,
        "gridFixed": False,
        "grid": [
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
        ],
    },
    "staves": {
        "superchargedFixed": False,
        "gridFixed": False,
        "grid": [
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
        ],
    },
    "freighter": {
        "superchargedFixed": False,
        "gridFixed": False,
        "grid": [
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
        ],
    },
    "nomad": {
        "superchargedFixed": True,
        "gridFixed": True,
        "grid": [
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True, "supercharged": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True, "supercharged": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": False},
                {"active": True},
                {"active": True, "supercharged": True},
                {"active": False},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": False},
                {"active": False},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
        ],
    },
    "pilgrim": {
        "superchargedFixed": True,
        "gridFixed": True,
        "grid": [
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True, "supercharged": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True, "supercharged": True},
            ],
            [
                {"active": False},
                {"active": True, "supercharged": True},
                {"active": True},
                {"active": False},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": False},
                {"active": False},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
        ],
    },
    "roamer": {
        "superchargedFixed": True,
        "gridFixed": True,
        "grid": [
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True, "supercharged": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True, "supercharged": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": False},
                {"active": True},
                {"active": True},
                {"active": False},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True, "supercharged": True},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
        ],
    },
    "nautilon": {
        "superchargedFixed": True,
        "gridFixed": True,
        "grid": [
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True, "supercharged": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True, "supercharged": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": False},
                {"active": True},
                {"active": True},
                {"active": False},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True, "supercharged": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
        ],
    },
    "colossus": {
        "superchargedFixed": True,
        "gridFixed": True,
        "grid": [
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True, "supercharged": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True, "supercharged": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True, "supercharged": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
        ],
    },
    "minotaur": {
        "superchargedFixed": True,
        "gridFixed": True,
        "grid": [
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True, "supercharged": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True, "supercharged": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": False},
                {"active": True},
                {"active": True},
                {"active": False},
                {"active": True, "supercharged": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
        ],
    },
    "exosuit": {
        "superchargedFixed": True,
        "gridFixed": False,
        "grid": [
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True, "supercharged": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True, "supercharged": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True, "supercharged": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
        ],
    },
}
