recommended_builds = {
    "nomad": [
        {
            "title": "Nomad",
            "layout": [
                [
                    {"tech": "radiation", "module": "NS", "adjacency_bonus": False},
                    {"tech": "toxic", "module": "AF", "adjacency_bonus": False},
                    {"tech": "thermal", "module": "TB", "adjacency_bonus": False},
                    {"tech": "cold", "module": "MH", "adjacency_bonus": False},
                    {"tech": "mining", "module": "Xc", "adjacency_bonus": True},
                    {
                        "tech": "mining",
                        "module": "ML",
                        "adjacency_bonus": True,
                        "supercharged": True,
                    },
                    {"tech": "mounted", "module": "Xc", "adjacency_bonus": True},
                    {"tech": "mounted", "module": "Xb", "adjacency_bonus": True},
                    {"tech": "boost", "module": "EB", "adjacency_bonus": True},
                    {"tech": "boost", "module": "Xa", "adjacency_bonus": True},
                ],
                [
                    {"tech": "icarus", "module": "FS", "adjacency_bonus": False},
                    {"tech": "fusion", "module": "FE", "adjacency_bonus": True},
                    {"tech": "fusion", "module": "Xb", "adjacency_bonus": True},
                    {"tech": "flamethrower", "module": "MF", "adjacency_bonus": False},
                    {"tech": "mining", "module": "Xa", "adjacency_bonus": True},
                    {"tech": "mining", "module": "Xb", "adjacency_bonus": True},
                    {"tech": "mounted", "module": "Xa", "adjacency_bonus": True},
                    {
                        "tech": "mounted",
                        "module": "MC",
                        "adjacency_bonus": True,
                        "supercharged": True,
                    },
                    {"tech": "boost", "module": "Xb", "adjacency_bonus": True},
                    {"tech": "boost", "module": "Xc", "adjacency_bonus": True},
                ],
                [
                    {"active": False},
                    {"tech": "fusion", "module": "Xc", "adjacency_bonus": True},
                    {
                        "tech": "fusion",
                        "module": "Xa",
                        "adjacency_bonus": True,
                        "supercharged": True,
                    },
                    {"active": False},
                    {"tech": "mining", "module": "AL", "adjacency_bonus": True},
                    {"tech": "radar", "module": "ER", "adjacency_bonus": False},
                    {"tech": "power", "module": "PR", "adjacency_bonus": False},
                    {"tech": "amplifier", "module": "RA", "adjacency_bonus": False},
                    {"active": False},
                    {"active": False},
                ],
                [
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                ],
                [
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                ],
                [
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                ],
            ],
        }
    ],
    "pilgrim": [
        {
            "title": "Pilgram",
            "layout": [
                [
                    {"tech": "radar", "module": "ER", "adjacency_bonus": False},
                    {"tech": "power", "module": "PR", "adjacency_bonus": False},
                    {"tech": "amplifier", "module": "RA", "adjacency_bonus": False},
                    {
                        "tech": "mining",
                        "module": "ML",
                        "adjacency_bonus": True,
                        "supercharged": True,
                    },
                    {"tech": "mining", "module": "Xc", "adjacency_bonus": True},
                    {"tech": "radiation", "module": "NS", "adjacency_bonus": True},
                    {"tech": "mounted", "module": "Xc", "adjacency_bonus": True},
                    {"tech": "mounted", "module": "Xb", "adjacency_bonus": True},
                    {"tech": "boost", "module": "EB", "adjacency_bonus": True},
                    {"tech": "boost", "module": "Xc", "adjacency_bonus": True},
                ],
                [
                    {"tech": "flamethrower", "module": "MF", "adjacency_bonus": False},
                    {"tech": "fusion", "module": "Xb", "adjacency_bonus": True},
                    {"tech": "fusion", "module": "FE", "adjacency_bonus": True},
                    {"tech": "mining", "module": "Xb", "adjacency_bonus": True},
                    {"tech": "mining", "module": "Xa", "adjacency_bonus": True},
                    {"tech": "toxic", "module": "AF", "adjacency_bonus": True},
                    {"tech": "mounted", "module": "Xb", "adjacency_bonus": True},
                    {"tech": "mounted", "module": "MC", "adjacency_bonus": True},
                    {"tech": "boost", "module": "Xb", "adjacency_bonus": True},
                    {
                        "tech": "boost",
                        "module": "Xa",
                        "adjacency_bonus": True,
                        "supercharged": True,
                    },
                ],
                [
                    {"active": False},
                    {
                        "tech": "fusion",
                        "module": "Xa",
                        "adjacency_bonus": True,
                        "supercharged": True,
                    },
                    {"tech": "fusion", "module": "Xc", "adjacency_bonus": True},
                    {"active": False},
                    {"tech": "mining", "module": "AL", "adjacency_bonus": True},
                    {"tech": "thermal", "module": "TB", "adjacency_bonus": False},
                    {"tech": "cold", "module": "MH", "adjacency_bonus": False},
                    {"tech": "icarus", "module": "FS", "adjacency_bonus": False},
                    {"active": False},
                    {"active": False},
                ],
                [
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                ],
                [
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                ],
                [
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                ],
            ],
        }
    ],
    "roamer": [
        {
            "title": "Roamer",
            "layout": [
                [
                    {"tech": "boost", "module": "EB", "adjacency_bonus": True},
                    {"tech": "boost", "module": "Xb", "adjacency_bonus": True},
                    {"tech": "mining", "module": "Xb", "adjacency_bonus": True},
                    {"tech": "mining", "module": "Xc", "adjacency_bonus": True},
                    {
                        "tech": "mounted",
                        "module": "MC",
                        "adjacency_bonus": True,
                        "supercharged": True,
                    },
                    {"tech": "mounted", "module": "Xa", "adjacency_bonus": True},
                    {"tech": "flamethrower", "module": "MF", "adjacency_bonus": True},
                    {"tech": "radar", "module": "ER", "adjacency_bonus": True},
                    {"tech": "slide", "module": "HS", "adjacency_bonus": True},
                    {"tech": "grip", "module": "GB", "adjacency_bonus": True},
                ],
                [
                    {"tech": "boost", "module": "Xa", "adjacency_bonus": True},
                    {"tech": "boost", "module": "Xc", "adjacency_bonus": True},
                    {
                        "tech": "mining",
                        "module": "ML",
                        "adjacency_bonus": True,
                        "supercharged": True,
                    },
                    {"tech": "mining", "module": "Xa", "adjacency_bonus": True},
                    {"tech": "mounted", "module": "Xb", "adjacency_bonus": True},
                    {"tech": "mounted", "module": "Xc", "adjacency_bonus": True},
                    {"tech": "amplifier", "module": "RA", "adjacency_bonus": True},
                    {"tech": "power", "module": "PR", "adjacency_bonus": True},
                    {"tech": "fusion", "module": "FE", "adjacency_bonus": True},
                    {"tech": "fusion", "module": "Xb", "adjacency_bonus": True},
                ],
                [
                    {"active": False},
                    {"tech": "icarus", "module": "FS", "adjacency_bonus": True},
                    {"tech": "mining", "module": "AL", "adjacency_bonus": True},
                    {"active": False},
                    {"tech": "radiation", "module": "NS", "adjacency_bonus": True},
                    {"tech": "thermal", "module": "TB", "adjacency_bonus": False},
                    {"tech": "cold", "module": "MH", "adjacency_bonus": False},
                    {"tech": "toxic", "module": "AF", "adjacency_bonus": False},
                    {"tech": "fusion", "module": "Xc", "adjacency_bonus": True},
                    {
                        "tech": "fusion",
                        "module": "Xa",
                        "adjacency_bonus": True,
                        "supercharged": True,
                    },
                ],
                [
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                ],
                [
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                ],
                [
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                ],
            ],
        }
    ],
    "nautilon": [
        {
            "title": "Nautilon",
            "layout": [
                [
                    {"tech": "sonar", "module": "HS", "adjacency_bonus": False},
                    {"tech": "nautilon", "module": "Xa", "adjacency_bonus": True},
                    {"tech": "nautilon", "module": "Xc", "adjacency_bonus": True},
                    {"active": True},
                    {
                        "tech": "humboldt",
                        "module": "Xa",
                        "adjacency_bonus": True,
                        "supercharged": True,
                    },
                    {"tech": "humboldt", "module": "OG", "adjacency_bonus": True},
                    {"active": True},
                    {"active": True},
                    {"active": True},
                    {"active": True},
                ],
                [
                    {"tech": "dredging", "module": "DL", "adjacency_bonus": False},
                    {
                        "tech": "nautilon",
                        "module": "NC",
                        "adjacency_bonus": True,
                        "supercharged": True,
                    },
                    {"tech": "nautilon", "module": "Xb", "adjacency_bonus": True},
                    {"active": True},
                    {"tech": "humboldt", "module": "Xc", "adjacency_bonus": True},
                    {"tech": "humboldt", "module": "Xb", "adjacency_bonus": True},
                    {"active": True},
                    {"active": True},
                    {"active": True},
                    {"active": True},
                ],
                [
                    {"active": False},
                    {"active": True},
                    {"active": True},
                    {"active": False},
                    {"tech": "icarus", "module": "FS", "adjacency_bonus": False},
                    {"tech": "humboldt", "module": "HD", "adjacency_bonus": True},
                    {"active": True},
                    {
                        "tech": "tethys",
                        "module": "TB",
                        "adjacency_bonus": False,
                        "supercharged": True,
                    },
                    {"active": True},
                    {"active": True},
                ],
                [
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                ],
                [
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                ],
                [
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                ],
            ],
        }
    ],
    "colossus": [
        {
            "title": "Colossus",
            "layout": [
                [
                    {"tech": "boost", "module": "EB", "adjacency_bonus": True},
                    {"tech": "boost", "module": "Xb", "adjacency_bonus": True},
                    {"tech": "mounted", "module": "MC", "adjacency_bonus": True},
                    {"tech": "mounted", "module": "Xa", "adjacency_bonus": True},
                    {"tech": "toxic", "module": "AF", "adjacency_bonus": False},
                    {"tech": "mining", "module": "AL", "adjacency_bonus": True},
                    {"tech": "icarus", "module": "FS", "adjacency_bonus": False},
                    {"tech": "fusion", "module": "FE", "adjacency_bonus": True},
                    {
                        "tech": "fusion",
                        "module": "Xa",
                        "adjacency_bonus": True,
                        "supercharged": True,
                    },
                    {"tech": "slide", "module": "HS", "adjacency_bonus": False},
                ],
                [
                    {"tech": "boost", "module": "Xa", "adjacency_bonus": True},
                    {"tech": "boost", "module": "Xc", "adjacency_bonus": True},
                    {"tech": "mounted", "module": "Xb", "adjacency_bonus": True},
                    {"tech": "mounted", "module": "Xc", "adjacency_bonus": True},
                    {"tech": "radiation", "module": "NS", "adjacency_bonus": False},
                    {"tech": "mining", "module": "Xa", "adjacency_bonus": True},
                    {"tech": "mining", "module": "Xc", "adjacency_bonus": True},
                    {
                        "tech": "fusion",
                        "module": "Xb",
                        "adjacency_bonus": True,
                        "supercharged": True,
                    },
                    {"tech": "fusion", "module": "Xc", "adjacency_bonus": True},
                    {"tech": "grip", "module": "GB", "adjacency_bonus": False},
                ],
                [
                    {"tech": "radar", "module": "ER", "adjacency_bonus": False},
                    {"tech": "amplifier", "module": "RA", "adjacency_bonus": False},
                    {"tech": "power", "module": "PR", "adjacency_bonus": False},
                    {"tech": "cold", "module": "MH", "adjacency_bonus": False},
                    {"tech": "thermal", "module": "TB", "adjacency_bonus": False},
                    {
                        "tech": "mining",
                        "module": "ML",
                        "adjacency_bonus": True,
                        "supercharged": True,
                    },
                    {"tech": "mining", "module": "Xb", "adjacency_bonus": True},
                    {"tech": "flamethrower", "module": "MF", "adjacency_bonus": False},
                    {"tech": "mineral", "module": "MP", "adjacency_bonus": False},
                    # {"tech": "drift", "module": "DS", "adjacency_bonus": False},
                    {"active": True},
                ],
                [
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                ],
                [
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                ],
                [
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                ],
            ],
        }
    ],
    "minotaur": [
        {
            "title": "Default Build",
            "layout": [
                [
                    {"tech": "array", "module": "RA", "adjacency_bonus": False},
                    {"tech": "environment", "module": "EC", "adjacency_bonus": False},
                    {"tech": "ariadnes", "module": "AF", "adjacency_bonus": False},
                    {"tech": "icarus", "module": "FS", "adjacency_bonus": False},
                    {"tech": "mining", "module": "AL", "adjacency_bonus": True},
                    {
                        "tech": "liquidator-left",
                        "module": "LL",
                        "adjacency_bonus": False,
                    },
                    {"tech": "daedalus", "module": "SG", "adjacency_bonus": True},
                    {
                        "tech": "daedalus",
                        "module": "Xa",
                        "adjacency_bonus": True,
                        "supercharged": True,
                    },
                    {
                        "tech": "liquidator-right",
                        "module": "LR",
                        "adjacency_bonus": True,
                    },
                    {
                        "tech": "liquidator-right",
                        "module": "Xb",
                        "adjacency_bonus": True,
                    },
                ],
                [
                    {
                        "tech": "minotaur",
                        "module": "Xa",
                        "adjacency_bonus": True,
                        "supercharged": True,
                    },
                    {"tech": "minotaur", "module": "MC", "adjacency_bonus": True},
                    {"tech": "minotaur", "module": "Xb", "adjacency_bonus": True},
                    {"tech": "mining", "module": "Xc", "adjacency_bonus": True},
                    {"tech": "mining", "module": "ML", "adjacency_bonus": True},
                    {"tech": "mining", "module": "Xb", "adjacency_bonus": True},
                    {"tech": "daedalus", "module": "Xb", "adjacency_bonus": True},
                    {"tech": "daedalus", "module": "DE", "adjacency_bonus": True},
                    {
                        "tech": "liquidator-right",
                        "module": "Xc",
                        "adjacency_bonus": True,
                    },
                    {
                        "tech": "liquidator-right",
                        "module": "Xa",
                        "adjacency_bonus": True,
                    },
                ],
                [
                    {"active": False},
                    {"tech": "minotaur", "module": "Xc", "adjacency_bonus": True},
                    {"tech": "bore", "module": "MB", "adjacency_bonus": False},
                    {"active": False},
                    {
                        "tech": "mining",
                        "module": "Xa",
                        "adjacency_bonus": True,
                        "supercharged": True,
                    },
                    {
                        "tech": "hardframe-left",
                        "module": "HL",
                        "adjacency_bonus": False,
                    },
                    {
                        "tech": "liquidator-legs",
                        "module": "LL",
                        "adjacency_bonus": False,
                    },
                    {"tech": "daedalus", "module": "Xc", "adjacency_bonus": True},
                    {
                        "tech": "liquidator-body",
                        "module": "LB",
                        "adjacency_bonus": False,
                    },
                    {"tech": "ai", "module": "AI", "adjacency_bonus": False},
                ],
                [
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                ],
                [
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                ],
                [
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                ],
            ],
        },
        {
            "title": "AI Support Build",
            "layout": [
                [
                    {"tech": "array", "module": "RA", "adjacency_bonus": False},
                    {"tech": "environment", "module": "EC", "adjacency_bonus": False},
                    {"tech": "ariadnes", "module": "AF", "adjacency_bonus": False},
                    {"tech": "icarus", "module": "FS", "adjacency_bonus": False},
                    {"active": True},
                    {
                        "tech": "liquidator-left",
                        "module": "LL",
                        "adjacency_bonus": False,
                    },
                    {"tech": "daedalus", "module": "SG", "adjacency_bonus": True},
                    {
                        "tech": "daedalus",
                        "module": "Xa",
                        "adjacency_bonus": True,
                        "supercharged": True,
                    },
                    {
                        "tech": "hardframe-right",
                        "module": "HR",
                        "adjacency_bonus": False,
                    },
                    {"active": True},
                ],
                [
                    {
                        "tech": "minotaur",
                        "module": "Xa",
                        "adjacency_bonus": True,
                        "supercharged": True,
                    },
                    {"tech": "minotaur", "module": "MC", "adjacency_bonus": True},
                    {"tech": "minotaur", "module": "Xb", "adjacency_bonus": True},
                    {"active": True},
                    {"active": True},
                    {"active": True},
                    {"tech": "daedalus", "module": "Xb", "adjacency_bonus": True},
                    {"tech": "daedalus", "module": "DE", "adjacency_bonus": True},
                    {"active": True},
                    {"active": True},
                ],
                [
                    {"active": False},
                    {"tech": "minotaur", "module": "Xc", "adjacency_bonus": True},
                    {"tech": "bore", "module": "MB", "adjacency_bonus": False},
                    {"active": False},
                    {"active": True},
                    {
                        "tech": "hardframe-left",
                        "module": "HL",
                        "adjacency_bonus": False,
                    },
                    {
                        "tech": "liquidator-legs",
                        "module": "LL",
                        "adjacency_bonus": False,
                    },
                    {"tech": "daedalus", "module": "Xc", "adjacency_bonus": True},
                    {
                        "tech": "liquidator-body",
                        "module": "LB",
                        "adjacency_bonus": False,
                    },
                    {"tech": "ai", "module": "AI", "adjacency_bonus": False},
                ],
                [
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                ],
                [
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                ],
                [
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                    {"active": False},
                ],
            ],
        },
    ],
    "exosuit": [
        {
            "title": "Exosuit",
            "layout": [
                [
                    {"tech": "refiner", "module": "PR", "adjacency_bonus": False},
                    {"tech": "skiff", "module": "ES", "adjacency_bonus": False},
                    {"tech": "hazmat", "module": "HG", "adjacency_bonus": False},
                    {"tech": "rebuilt", "module": "Xb", "adjacency_bonus": True},
                    {
                        "tech": "forbidden",
                        "module": "Xa",
                        "adjacency_bonus": True,
                        "supercharged": True,
                    },
                    {"tech": "defense", "module": "Xb", "adjacency_bonus": True},
                    {"tech": "coolant", "module": "Xb", "adjacency_bonus": True},
                    {"tech": "hazard", "module": "HP", "adjacency_bonus": True},
                    {"tech": "anomaly", "module": "AS", "adjacency_bonus": True},
                    {"tech": "toxin", "module": "Xb", "adjacency_bonus": True},
                ],
                [
                    {"tech": "nutrient", "module": "NI", "adjacency_bonus": True},
                    {"tech": "jetpack", "module": "JP", "adjacency_bonus": True},
                    {"tech": "jetpack", "module": "WJ", "adjacency_bonus": True},
                    {"tech": "rebuilt", "module": "Xa", "adjacency_bonus": True},
                    {"tech": "forbidden", "module": "Xb", "adjacency_bonus": True},
                    {"tech": "defense", "module": "Xa", "adjacency_bonus": True},
                    {"tech": "coolant", "module": "Xa", "adjacency_bonus": True},
                    {"tech": "protection", "module": "SL", "adjacency_bonus": True},
                    {
                        "tech": "protection",
                        "module": "Xa",
                        "adjacency_bonus": True,
                        "supercharged": True,
                    },
                    {"tech": "toxin", "module": "Xa", "adjacency_bonus": True},
                ],
                [
                    {"tech": "jetpack", "module": "AB", "adjacency_bonus": True},
                    {"tech": "jetpack", "module": "Xb", "adjacency_bonus": True},
                    {
                        "tech": "jetpack",
                        "module": "Xa",
                        "adjacency_bonus": True,
                        "supercharged": True,
                    },
                    {"tech": "rebuilt", "module": "Xc", "adjacency_bonus": True},
                    {"tech": "forbidden", "module": "Xc", "adjacency_bonus": True},
                    {"tech": "defense", "module": "Xc", "adjacency_bonus": True},
                    {"tech": "coolant", "module": "Xc", "adjacency_bonus": True},
                    {"tech": "protection", "module": "Xb", "adjacency_bonus": True},
                    {"tech": "protection", "module": "Xc", "adjacency_bonus": True},
                    {"tech": "toxin", "module": "Xc", "adjacency_bonus": True},
                ],
                [
                    {"tech": "exocraft", "module": "ES", "adjacency_bonus": True},
                    {"tech": "jetpack", "module": "NS", "adjacency_bonus": True},
                    {"tech": "jetpack", "module": "Xc", "adjacency_bonus": True},
                    {"tech": "translators", "module": "Ta", "adjacency_bonus": True},
                    {"tech": "translators", "module": "Tb", "adjacency_bonus": True},
                    {"tech": "aeration", "module": "Xb", "adjacency_bonus": True},
                    {"tech": "radiation", "module": "Xb", "adjacency_bonus": True},
                    {"tech": "coolant", "module": "CN", "adjacency_bonus": True},
                    {"tech": "toxin", "module": "TS", "adjacency_bonus": True},
                    {"tech": "thermic", "module": "Xb", "adjacency_bonus": True},
                ],
                [
                    {"tech": "life", "module": "Xc", "adjacency_bonus": True},
                    {"tech": "life", "module": "Xb", "adjacency_bonus": True},
                    {"tech": "life", "module": "RR", "adjacency_bonus": False},
                    {"tech": "translators", "module": "Tc", "adjacency_bonus": True},
                    {"tech": "translators", "module": "Td", "adjacency_bonus": True},
                    {"tech": "aeration", "module": "Xa", "adjacency_bonus": True},
                    {"tech": "radiation", "module": "Xa", "adjacency_bonus": True},
                    {"tech": "radiation", "module": "RD", "adjacency_bonus": True},
                    {"tech": "thermic", "module": "TL", "adjacency_bonus": True},
                    {"tech": "thermic", "module": "Xa", "adjacency_bonus": True},
                ],
                [
                    {"tech": "life", "module": "Xa", "adjacency_bonus": True},
                    {"tech": "life", "module": "LS", "adjacency_bonus": True},
                    {"tech": "life", "module": "OR", "adjacency_bonus": True},
                    {"tech": "remembrance", "module": "RM", "adjacency_bonus": True},
                    {"tech": "starseed", "module": "SS", "adjacency_bonus": True},
                    {"tech": "aeration", "module": "Xc", "adjacency_bonus": True},
                    {"tech": "aeration", "module": "AM", "adjacency_bonus": True},
                    {"tech": "radiation", "module": "Xc", "adjacency_bonus": True},
                    {"tech": "thermic", "module": "Xc", "adjacency_bonus": True},
                    {"tech": "pressure", "module": "PM", "adjacency_bonus": True},
                ],
            ],
        }
    ],
}
