recommended_builds = {
    "nomad": {
        "layout": [
            [
                {"tech": "radiation", "module": "NS", "adjacency_bonus": False},
                {"tech": "toxic", "module": "AF", "adjacency_bonus": False},
                {"tech": "thermal", "module": "TB", "adjacency_bonus": False},
                {"tech": "cold", "module": "MH", "adjacency_bonus": False},
                {"tech": "mining", "module": "Xc", "adjacency_bonus": True},
                {"tech": "mining", "module": "ML", "adjacency_bonus": True, "supercharged": True},
                {"tech": "mounted", "module": "Xc", "adjacency_bonus": True},
                {"tech": "mounted", "module": "Xb", "adjacency_bonus": True},
                {"tech": "boost", "module": "EB", "adjacency_bonus": True},
                {"tech": "boost", "module": "Xa", "adjacency_bonus": True},
            ],
            [
                {"tech": "icarus", "module": "FS", "adjacency_bonus": False},
                {"tech": "fusion", "module": "FE", "adjacency_bonus": True},
                {"tech": "fusion", "module": "Xb", "adjacency_bonus": True},
                {"tech": "flamethrower", "module": "MF", "adjacency_bonus": False},
                {"tech": "mining", "module": "Xa", "adjacency_bonus": True},
                {"tech": "mining", "module": "Xb", "adjacency_bonus": True},
                {"tech": "mounted", "module": "Xb", "adjacency_bonus": True},
                {"tech": "mounted", "module": "MC", "adjacency_bonus": True, "supercharged": True},
                {"tech": "boost", "module": "Xb", "adjacency_bonus": True},
                {"tech": "boost", "module": "Xc", "adjacency_bonus": True},
            ],
            [
                {"active": False},
                {"tech": "fusion", "module": "Xc", "adjacency_bonus": True},
                {"tech": "fusion", "module": "Xa", "adjacency_bonus": True, "supercharged": True},
                {"active": False},
                {"tech": "mining", "module": "AL", "adjacency_bonus": True},
                {"tech": "radar", "module": "ER", "adjacency_bonus": False},
                {"tech": "power", "module": "PR", "adjacency_bonus": False},
                {"tech": "amplifier", "module": "RA", "adjacency_bonus": False},
                {"active": False},
                {"active": False},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
        ]
    },
    "pilgram": {
        "layout": [
            [
                {"tech": "radar", "module": "ER", "adjacency_bonus": False},
                {"tech": "power", "module": "PR", "adjacency_bonus": False},
                {"tech": "amplifier", "module": "RA", "adjacency_bonus": False},
                {"tech": "mining", "module": "ML", "adjacency_bonus": True, "supercharged": True},
                {"tech": "mining", "module": "Xc", "adjacency_bonus": True},
                {"tech": "radiation", "module": "NS", "adjacency_bonus": True},
                {"tech": "mounted", "module": "Xc", "adjacency_bonus": True},
                {"tech": "mounted", "module": "Xb", "adjacency_bonus": True},
                {"tech": "boost", "module": "EB", "adjacency_bonus": True},
                {"tech": "boost", "module": "Xc", "adjacency_bonus": True},
            ],
            [
                {"tech": "flamethrower", "module": "MF", "adjacency_bonus": False},
                {"tech": "fusion", "module": "Xb", "adjacency_bonus": True},
                {"tech": "fusion", "module": "FE", "adjacency_bonus": True},
                {"tech": "mining", "module": "Xb", "adjacency_bonus": True},
                {"tech": "mining", "module": "Xa", "adjacency_bonus": True},
                {"tech": "toxic", "module": "AF", "adjacency_bonus": True},
                {"tech": "mounted", "module": "Xb", "adjacency_bonus": True},
                {"tech": "mounted", "module": "MC", "adjacency_bonus": True},
                {"tech": "boost", "module": "Xb", "adjacency_bonus": True},
                {"tech": "boost", "module": "Xa", "adjacency_bonus": True, "supercharged": True},
            ],
            [
                {"active": False},
                {"tech": "fusion", "module": "Xa", "adjacency_bonus": True, "supercharged": True},
                {"tech": "fusion", "module": "Xc", "adjacency_bonus": True},
                {"active": False},
                {"tech": "mining", "module": "AL", "adjacency_bonus": True},
                {"tech": "thermal", "module": "TB", "adjacency_bonus": False},
                {"tech": "cold", "module": "MH", "adjacency_bonus": False},
                {"tech": "icarus", "module": "FS", "adjacency_bonus": False},
                {"active": False},
                {"active": False},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
        ]
    },
    "roamer": {
        "layout": [
            [
                {"tech": "boost", "module": "EB", "adjacency_bonus": True},
                {"tech": "boost", "module": "Xb", "adjacency_bonus": True},
                {"tech": "mining", "module": "Xb", "adjacency_bonus": True},
                {"tech": "mining", "module": "Xc", "adjacency_bonus": True},
                {"tech": "mounted", "module": "MC", "adjacency_bonus": True, "supercharged": True},
                {"tech": "mounted", "module": "Xa", "adjacency_bonus": True},
                {"tech": "flamethrower", "module": "MF", "adjacency_bonus": True},
                {"tech": "radar", "module": "ER", "adjacency_bonus": True},
                {"tech": "slide", "module": "HS", "adjacency_bonus": True},
                {"tech": "grip", "module": "GB", "adjacency_bonus": True},
            ],
            [
                {"tech": "boost", "module": "Xa", "adjacency_bonus": True},
                {"tech": "boost", "module": "Xc", "adjacency_bonus": True},
                {"tech": "mining", "module": "ML", "adjacency_bonus": True, "supercharged": True},
                {"tech": "mining", "module": "Xa", "adjacency_bonus": True},
                {"tech": "mounted", "module": "Xb", "adjacency_bonus": True},
                {"tech": "mounted", "module": "Xc", "adjacency_bonus": True},
                {"tech": "amplifier", "module": "RA", "adjacency_bonus": True},
                {"tech": "power", "module": "PR", "adjacency_bonus": True},
                {"tech": "fusion", "module": "FE", "adjacency_bonus": True},
                {"tech": "fusion", "module": "Xb", "adjacency_bonus": True},
            ],
            [
                {"active": False},
                {"tech": "icarus", "module": "FS", "adjacency_bonus": True},
                {"tech": "mining", "module": "AL", "adjacency_bonus": True},
                {"active": False},
                {"tech": "radiation", "module": "NS", "adjacency_bonus": True},
                {"tech": "thermal", "module": "TB", "adjacency_bonus": False},
                {"tech": "cold", "module": "MH", "adjacency_bonus": False},
                {"tech": "toxic", "module": "AF", "adjacency_bonus": False},
                {"tech": "fusion", "module": "Xc", "adjacency_bonus": True},
                {"tech": "fusion", "module": "Xa", "adjacency_bonus": True, "supercharged": True},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
        ]
    },
    "naution": {
        "layout": [
            [
                {"tech": "sonar", "module": "HS", "adjacency_bonus": False},
                {"tech": "naution", "module": "Xa", "adjacency_bonus": True},
                {"tech": "naution", "module": "Xc", "adjacency_bonus": True},
                {"active": True},
                {"tech": "humboldt", "module": "Xa", "adjacency_bonus": True, "supercharged": True},
                {"tech": "humboldt", "module": "OG", "adjacency_bonus": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"tech": "dredging", "module": "DL", "adjacency_bonus": False},
                {"tech": "naution", "module": "NC", "adjacency_bonus": True, "supercharged": True},
                {"tech": "naution", "module": "Xb", "adjacency_bonus": True},
                {"active": True},
                {"tech": "humboldt", "module": "Xc", "adjacency_bonus": True},
                {"tech": "humboldt", "module": "Xb", "adjacency_bonus": True},
                {"active": True},
                {"active": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": False},
                {"active": True},
                {"active": True},
                {"active": False},
                {"tech": "icarus", "module": "FS", "adjacency_bonus": False},
                {"tech": "humboldt", "module": "HD", "adjacency_bonus": True},
                {"active": True},
                {"tech": "tethys", "module": "TB", "adjacency_bonus": False, "supercharged": True},
                {"active": True},
                {"active": True},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
            [
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
                {"active": False},
            ],
        ]
    },
    "colossus": {
        "layout": [
            [
                {"tech": "boost", "module": "EB", "adjacency_bonus": True},
                {"tech": "boost", "module": "Xb", "adjacency_bonus": True},
                {"tech": "mounted", "module": "MC", "adjacency_bonus": True},
                {"tech": "mounted", "module": "Xa", "adjacency_bonus": True},
                {"tech": "toxic", "module": "AF", "adjacency_bonus": False},
                {"tech": "mining", "module": "AL", "adjacency_bonus": True},
                {"tech": "icarus", "module": "FS", "adjacency_bonus": False},
                {"tech": "fusion", "module": "FE", "adjacency_bonus": True},
                {"tech": "fusion", "module": "Xa", "adjacency_bonus": True, "supercharged": True},
                {"tech": "slide", "module": "HS", "adjacency_bonus": False},
            ],
            [
                {"tech": "boost", "module": "Xa", "adjacency_bonus": True},
                {"tech": "boost", "module": "Xc", "adjacency_bonus": True},
                {"tech": "mounted", "module": "Xb", "adjacency_bonus": True},
                {"tech": "mounted", "module": "Xc", "adjacency_bonus": True},
                {"tech": "radiation", "module": "NS", "adjacency_bonus": False},
                {"tech": "mining", "module": "Xa", "adjacency_bonus": True},
                {"tech": "mining", "module": "Xc", "adjacency_bonus": True},
                {"tech": "fusion", "module": "Xb", "adjacency_bonus": True, "supercharged": True},
                {"tech": "fusion", "module": "Xc", "adjacency_bonus": True},
                {"tech": "grip", "module": "GB", "adjacency_bonus": False},
            ],
            [
                {"tech": "radar", "module": "ER", "adjacency_bonus": False},
                {"tech": "amplifier", "module": "RA", "adjacency_bonus": False},
                {"tech": "power", "module": "PR", "adjacency_bonus": False},
                {"tech": "cold", "module": "MH", "adjacency_bonus": False},
                {"tech": "thermal", "module": "TB", "adjacency_bonus": False},
                {"tech": "mining", "module": "ML", "adjacency_bonus": True, "supercharged": True},
                {"tech": "mining", "module": "Xb", "adjacency_bonus": True},
                {"tech": "flamethrower", "module": "MF", "adjacency_bonus": False},
                {"tech": "foo", "module": "Xc", "adjacency_bonus": True},
                {"tech": "drift", "module": "DS", "adjacency_bonus": False},
            ],
        ]
    },
}
